library/library/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('library_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

library/library_app/urls.py
from . import views
from django.urls import path
app_name = 'library_app'
urlpatterns = [

    path('', views.index, name='index'),
    path('book/<int:book_id>/', views.detail, name='detail'),
    path('add/', views.add_book, name='add_book'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

library/library_app/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

library/library_app/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name','desc','img']

library/library_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Book
from . forms import BookForm
# Create your views here.
def index(request):
    book = Book.objects.all()
    context = {
        'book_list': book
    }
    return render(request,"index.html",context)

def detail(request, book_id):
    book = Book.objects.get(id=book_id)
    return render(request,"detail.html",{'book':book})

def add_book(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        img = request.FILES['img']
        book = Book(name=name, desc=desc, img=img)
        book.save()
    return render(request,'add.html')

def update(request,id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES,instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'book': book})

def delete(request,id):
    if request.method == 'POST':
        movie = Book.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

library/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="name" placeholder="Enter your Book name"><br>
        <input type="text" name="desc" placeholder="Enter Book description"><br>
        <input type="file" name="img" ><br>
        <input type="submit" value="submit"><br>
    <a class="fcc-btn text-left" href="{% url 'library_app:index' %}">Back To Homepage</a>
</form>

{% endblock %}

library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OnlineBookStore</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and Text -->
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        Online Book Store
    </a>
    <a class="fcc-btn text-right" href="{% url 'library_app:add_book' %}">Add Book</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

library/templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form method="POST">
  {% csrf_token %}
  Are you sure to delete this book?
  <input type="submit" value="delete">
</form>

{% endblock %}

library/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{book.img.url}}" width="300" height="400">
        </div>
<div class="col-md-8">
    <h3 style="color:white">{{book.name}}</h3>
    <h4>{{book.desc}}</h4>
    <a class="btn btn-warning" href="{% url 'library_app:update' book.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'library_app:delete' book.id %}">delete</a>
</div>
    </div>
</div>
{% endblock %}

library/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="update">
</form>
{% endblock %}

library/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in book_list %}
        <div class="col-md-3">
            <div class="card" style="width: 16rem; height:24rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'library_app:detail' i.id%}" class="btn btn-primary">view details</a>
  </div>
</div><br>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}